### ISSUE TITLE
Enhance contributing guide

### ISSUE THREAD

**Issue by atilag** [QISKit/qiskit-sdk-py#100]
The contributing guide should include examples and a better description of the workflow expected from contributions. Our branch model, release cycle, etc.

**Comment by diego-plan9** [comment]
We probably also want to elaborate or be a bit more explicit in regards to the style conventions (maybe with the "official" tools to be used for the style checks, as raised during #106).

**Comment by atilag** [comment]
Yeah, let's do it.
About the expected workflow for contributors, let's stick to the classical: Issue -> Discussion -> Implementation -> Pull Request. The point here is to have a previous conversation about possible solutions for a bug/feature, before someone starts implementing something. This way we'll make sure that the implementation has a better fit in our code base.

BTW, I have created a new doc: DEVELOPMENT_CYCLE.md, explaining our branch model and release cycle, we should probably link to it from the CONTRIBUTING.md doc.

**Comment by lbello** [comment]
When is this issue considered done?

**Comment by atilag** [comment]
Yep, we should have a review and spot deficiencies in the doc.
