### ISSUE TITLE
Can't find eval_hamiltonian in optimization.py

### ISSUE THREAD

**Issue by hellmersjl3ds** [QISKit/qiskit-sdk-py#114]
There used to be a function eval_hamiltonian in qiskit.tools.apps.optimization.py that seems to have gone missing.  Ditto for group_paulis.

I did a search for them and I can't find them anywhere is QISKit.  Were they replaced?

## Expected Behavior
I should be able to import the function such as
from qiskit.tools.apps.optimization import eval_hamiltonian

## Current Behavior
ImportError: cannot import name 'eval_hamiltonian'

## Possible Solution
Identify where those functions went.

## Steps to Reproduce (for bugs)
from qiskit.tools.apps.optimization import eval_hamiltonian

## Context
Trying to run the Quantum Chemistry tutorial

## Your Environment
* Environment name and version (e.g. Python 3.6): Python 3.6
* Operating System and version: Ubuntu 16.04

**Comment by hellmersjl3ds** [comment]
If this is something that needs to be done I'm willing to make the contribution.

**Comment by jaygambetta** [comment]
This should be in pr #104 104 the team is reviewing this pr now. If you want to look at please do and if you have suggest or want to add additions i would suggest commenting with @antoniomezzacapo so that there is no repeated work (or less repeated work :-))

**Comment by hellmersjl3ds** [comment]
That looks OK to me.  I'd be happy to test it out, if that's part of the process.

**Comment by atilag** [comment]
Closing this bug as it seems it was implemented in #104
