### ISSUE TITLE
Link to QISKit tutorials in some way.

### ISSUE THREAD

**Issue by atilag** [QISKit/qiskit-sdk-py#134]
After reviewing a contribution from a colleague (thanks Andreas!) I saw something that will love to discuss here - QISKit Tutorials are strongly related to the SDK, so I was thinking that maybe we could provide a way to include or link QISKit tutorials repository into the SDK. I guess that this could make things easier for someone who wants to work in the tutorials using QISKit development (master) branch . What do you think team?

I'd propose any of these approaches:
* As a submodule linked to a "tutorials" directory onto root dir.
* Creating a Makefile target that will clone the repository onto root dir.

**Comment by ewinston** [comment]
Are git subtrees worth considering? Perhaps something minimal to do is at least make sure all qiskit- repos follow the same branch structure so e.g. stable works across all. Would it be possible to have a solution which doesn't make working with the separate repos too complicated (from a git perspective). For instance maybe we could just create a super repo which pulls in all submodules/subtrees?

**Comment by diego-plan9** [comment]
> Perhaps something minimal to do is at least make sure all qiskit- repos follow the same branch structure so e.g. stable works across all

Good point - and I believe this is actually the issue we need to address before deciding the best way to include the tutorials, as we have a bit of a mismatch between the users that will clone this repository (defaulting to `master`) and the users that want to run the tutorials (that are intended to be used with `stable`, and the only recommendation on the tutorials repository README is to install via `pip`).

**Comment by atilag** [comment]
> Are git subtrees worth considering?
Sure, I'd go for subtrees instead of submodules.
And agree with both of you, let's first normalize tutorials branching structure so the SDK and the tutorials are aligned.

**Comment by atilag** [comment]
We are going to keep these repositories separated for now, as we rather enforce people using pip package instead of git repository.
