### ISSUE TITLE
Temporary file /tmp/parsetab.py

### ISSUE THREAD

**Issue by nikomoll** [QISKit/qiskit-sdk-py#137]
I think when parsing qiskit writes a temporary file /tmp/parsetab.py . This poses a problem if two users use qiskit on the same machine. The temporary file should be unique to each user.

## Expected Behavior
Temporary file should be unique for each user.

## Current Behavior
Temporary file is not unique for each user which leads to write conflicts.

## Possible Solution
Add user name to the parsetab file.

## Steps to Reproduce (for bugs)
ls -l /tmp/parsetab.py

**Comment by atilag** [comment]
Yep, you are right!
Thanks for reporting! ... will be fixed ASAP.

**Comment by diego-plan9** [comment]
Closed via #139  - as usual, thanks for reporting!

**Comment by atilag** [comment]
@nikomoll We have issued a new release: 0.3.9 which fixes this issue as well. You can update it via pip  (if you are using pip): `pip install --upgrade qiskit`
