### ISSUE TITLE
Evaluate linter alternatives to pylint.

### ISSUE THREAD

**Issue by atilag** [QISKit/qiskit-sdk-py#149]
Following up conversation from PR #147 I would love to have a little discussion about what other linter alternatives we could integrate within the SDK. 
I think there's an agreement to not integrating with multiple linter tools, so lets choose one.
We are using `pylint` from the beginning and I guess that the main reason is because it's considered a standard de facto, but we are having a bad time going full free of warnings and there's a lot of false positives, which I guess is something we can afford... but, it's kind of annoying.
My question for the real experts (@diego-plan9  @cclauss), is there anything we can do with `flake8` that we can't do (or it's too cumbersome) with `pylint`?

**Comment by cclauss** [comment]
Both pylint and flake8 live under the [Python Code Quality Authority](https://github.com/PyCQA) and we continue to see nice convergence in the progress of these two tools.  Personally, I like flake8 and will from time to time run it over the codebase to look for issues but I have no problem with sticking with pylint as the official approach for this repo.  I have taken flake8 out of #147 and changed the PR name to reflect its new focus on pylint.  There are a few open pylint issues to resolve but there are suggestions in that PR to guide us towards some solutions.

**Comment by atilag** [comment]
Gonna close this Issue to keep repo clean. 
Please, feel free to reopen it if want to resume the discussion.
