### ISSUE TITLE
Make random context explicity local for every circuit run.

### ISSUE THREAD

**Issue by atilag** [QISKit/qiskit-sdk-py#150]
Our concurrency model saves us from having two circuits running at the same time, interfere each other when setting up the random context:
```python
if circuit['config']['seed'] is None:
    random.seed(random.getrandbits(32))
else:
    random.seed(circuit['config']['seed'])
```
... because we are using `ProcessPoolExecutor`, hence we are using processes for running every circuit in parallel. **But** it's a poor design to trust in runtime implementation for this to work, so we want to fix this situation.

**Newcomers**
As this is not a critical bug, and it has a very simple solution, I think is a good opportunity for people who wants to get their head around the contributing workflow, to take this issue and fix it.

## Expected Behavior
Circuit random context should not change if another circuit is running at the same time.

## Possible Solution
Don't want to give too many clues for people who want to give a try, but this could be a possible solution:
```python
local_random = random.Random()
```
... we would be more than glad if another elegant and simple solution comes up :)

**The point here is to make sure that random numbers generation on every circuit do not interfere each other when multiple circuits are running in parallel.**

## Your Environment

* Version used: qiskit 0.4 (`master`) ... qiskit 0.3.x (`stable`) is not affected.
* Environment name and version (e.g. Python 3.6.1): Python 3.5 and 3.6

**Comment by hellmersjl3ds** [comment]
I'll volunteer for this one.  I guess the first thing is to do a pull request?

**Comment by atilag** [comment]
Thanks for stepping up @hellmersjl3ds !
Yes, we usually want a prior discussion to see what's the best approach to implement the feature/fix, but in this  is case is an easy one, so go ahead and make a PR. I'll be the reviewer :)

**Comment by atilag** [comment]
Hi @hellmersjl3ds , if you need some help here, let me know! :)

**Comment by hellmersjl3ds** [comment]
Looking at this now.  Is there an use case that is failing for this?

**Comment by atilag** [comment]
Not really, because the way CPython implements concurrency. Anyway, as stated in the bug description this is a poor design so we want to fix it. You won't be able to test whether your fix actually fixes the problem, fortunately the fix should be pretty, I could review it without testing.

**Comment by atilag** [comment]
PR Merged!
Thanks @hellmersjl3ds 
Happy holidays ;)
