### ISSUE TITLE
Error in evaluating Pauli-list style Hamiltonian

### ISSUE THREAD

**Issue by itoko** [QISKit/qiskit-sdk-py#154]
tools.optimization.eval_hamiltonian() fails by error if hamiltonian is given as pauli list.

## Possible Solution
I found an obvious invalid source format, so I'll fix it.

## Steps to Reproduce (for bugs)
1. Open qiskit-tutorial/4_application/quantum_chemistry.ipynb (latest stable branch) with qiskit-sdk-py (latest stable branch)
2. Just before the first definition of cost_function(), insert `H = pauli_list`
3. Run the notebook
-> AttributeError: 'dict' object has no attribute 'conjugate' at line 344

## Context
Trying to understand tutorial more by running it with slightly modified parameters

**Comment by diego-plan9** [comment]
Closed by #155
