### ISSUE TITLE
[WIP] get rid of float in favor of sympy

### ISSUE THREAD

**Issue by 1ucian0** [QISKit/qiskit-sdk-py#158]
Float is a source of imprecision, as #111 shows. I'm working on a pull request to get rid of float (and math) in favor of sympy, as suggested to @awcross1.

Please, comment on this issue if you have any thought.

**Comment by nonhermitian** [comment]
Why not just check if the value is one to floating point precision, and then just set to one if so?  Adding an entire dependency for a single corner-case is probably not the way to go.

**Comment by lbello** [comment]
Hi @nonhermitian ,
There are several situations where dealing with floats is hard. There are several zero checks and simplifications that we can delegate to this library.

**Comment by atilag** [comment]
@lbello what's the status of this issue? I know there have been several commits regarding float to sympy migration.

**Comment by 1ucian0** [comment]
For sure, the tools are still using floats. I will take a look to the rest. If it's just the tools, I would probably consider this done for now.

**Comment by 1ucian0** [comment]
The coming approach is to handle sympy and numpy options. Give option to the user to have a symbolic representation or an efficient numpy as numbers. Soon, a PR about this.
