### ISSUE TITLE
mapper does not remove u1(2 * pi)

### ISSUE THREAD

**Issue by itoko** [QISKit/qiskit-sdk-py#159]
As @decodoku mentions in #157, mapper leaves two consecutive H gates as u1(2 * pi). 
I think this is closely related to #158 

## Expected Behavior
Identify gates equivalent with id e.g. u1(2 * pi), and remove it from the circuit

## Possible Solution
Improve mapper.optimize_1q_gates?

## Steps to Reproduce (for bugs)
See #157 
Run
```
from qiskit import QuantumProgram
import Qconfig

qp = QuantumProgram()
qp.set_api(Qconfig.APItoken, Qconfig.config["url"])

qr = qp.create_quantum_register('qr',2)
cr = qp.create_classical_register('cr',2)
qc = qp.create_circuit('Bell',[qr],[cr])
qc.h(qr[0])
qc.cx(qr[1], qr[0])
qc.cx(qr[1], qr[0])
qc.cx(qr[1], qr[0])
qc.measure(qr[0], cr[0])
qc.measure(qr[1], cr[1])

backend = 'ibmqx4'
cmap = qp.get_backend_configuration(backend)['coupling_map']
qobj = qp.compile(["Bell"], backend=backend, coupling_map=cmap)
print(qp.get_compiled_qasm(qobj,"Bell"))
```

Output will be:
```
OPENQASM 2.0;
include "qelib1.inc";
qreg q[2];
creg cr[2];
u1(6.283185307179586) q[1];
u2(0.0,3.141592653589793) q[0];
cx q[1],q[0];
u1(6.283185307179586) q[0];
u1(6.283185307179586) q[1];
cx q[1],q[0];
u1(6.283185307179586) q[0];
u1(6.283185307179586) q[1];
cx q[1],q[0];
u2(0.0,3.141592653589793) q[0];
measure q[0] -> cr[1];
u2(0.0,3.141592653589793) q[1];
measure q[1] -> cr[0];
```

**Comment by rraymondhp** [comment]
To my understanding, `u1` is done by software (zero error), so this practically has no decoherence/noise effects?

**Comment by itoko** [comment]
Yes if you see only `u1`. But, for this example, if we can cancel out u1, then we can also cancel out two cx q[1],q[0], that will reduce noise.

**Comment by itoko** [comment]
Umm. In current mapper, swap_mapper, direction_mapper, cx_cancellation, optimize_1q_gates run in this order. To cancel cx in this case, we may need to run cx_cancellation before direction_mapper or after optimize_1q_gates no matter if we improve optimize_1q_gates or not...

**Comment by lbello** [comment]
Is this paper relate to this issue? https://pdfs.semanticscholar.org/a491/a603af08bf7337d7ebe94c09cf702891c64b.pdf

**Comment by jaygambetta** [comment]
this is a bug and we should fix @awcross1 can you look at this as we should not set identities into the circuit and not removed pre and post gates.

**Comment by awcross1** [comment]
PR #171 should address this issue. Further CNOT simplifications would require modifying the set of passes, which will be more natural after we implement the new architecture.
