### ISSUE TITLE
ImportError: cannot import name 'basicplotter'

### ISSUE THREAD

**Issue by sgeron** [QISKit/qiskit-sdk-py#17]
**In the tutorial4developer, when I run the following cell:**

import sys
sys.path.append("")
from qiskit import QuantumProgram
import Qconfig

**I have an "ImportError: cannot import name 'basicplotter'" with the following detail:**

ImportError                               Traceback (most recent call last)
<ipython-input-35-dd3255bb9133> in <module>()
      2 sys.path.append("") # solve the relative dependencies if you clone QISKit from the Git repo and use like a global.
      3 print (sys.path)
----> 4 from qiskit import QuantumProgram
      5 import Qconfig

~/py/qiskit-sdk-py/qiskit/__init__.py in <module>()
      8 from ._qiskitexception import QISKitException
      9 import qiskit.extensions.standard
---> 10 from ._quantumprogram import QuantumProgram

~/py/qiskit-sdk-py/qiskit/_quantumprogram.py in <module>()
     28 # use the external IBMQuantumExperience Library
     29 from IBMQuantumExperience.IBMQuantumExperience import IBMQuantumExperience
---> 30 from . import basicplotter
     31 
     32 # Stable Modules

ImportError: cannot import name 'basicplotter'

**Comment by sgeron** [comment]
I went through a whole new installation of Anaconda&Qiskit, following exactly the required procedure (previously, I had tried it without Anaconda, installing the packages myself). I still have a similar problem :


**from qiskit import QuantumProgram**
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-dbe36dd11274> in <module>()
**----> 1 from qiskit import QuantumProgram**

/Users/sgeron/AnacondaProjects/qiskit-sdk-py/qiskit/__init__.py in <module>()
      8 from ._qiskitexception import QISKitException
      9 import qiskit.extensions.standard
**---> 10 from ._quantumprogram import QuantumProgram**

/Users/sgeron/AnacondaProjects/qiskit-sdk-py/qiskit/_quantumprogram.py in <module>()
     27 from collections import Counter
     28 # use the external IBMQuantumExperience Library
**---> 29 from IBMQuantumExperience.IBMQuantumExperience import IBMQuantumExperience**
     30 from . import basicplotter
     31 

**ModuleNotFoundError: No module named 'IBMQuantumExperience'**

**Comment by alexandrupaler** [comment]
check the issue regarding Makefile which I filed. You have two options: 
a) remove the conda environment called QISKITEnv and then run make env-dev, or
b) just execute the single line from the Makefile which corresponds to env-dev

**Comment by jaygambetta** [comment]
@sgeron do you still get this with the latest update. We have split the tutorials and qiskit. If you switch to r0.3 please run make test and it should update all the requirements. 

https://github.com/QISKit/qiskit-tutorial

@alexandrupaler i agree the makefile has the error that if you try to make it with it with QISKit env already present.

**Comment by sgeron** [comment]
Thanks @jaygambetta and @alexandrupaler !

So I uninstalled everything and tried to switch to r0.3. After cloning from github, I get an error message when running **"make env"**:

--------------------------------

sgeron@freifmac0033643:~/AnacondaProjects/qiskit-sdk-py$ **make env**
conda create -y -n QISKitenv python=3
Fetching package metadata .........
Solving package specifications: .

Package plan for installation in environment /Users/sgeron/anaconda/envs/QISKitenv:

The following NEW packages will be INSTALLED:

    openssl:    1.0.2l-0     
    pip:        9.0.1-py36_1 
    python:     3.6.2-0      
    readline:   6.2-2        
    setuptools: 27.2.0-py36_0
    sqlite:     3.13.0-0     
    tk:         8.5.18-0     
    wheel:      0.29.0-py36_0
    xz:         5.2.2-1      
    zlib:       1.2.8-3      

#
# To activate this environment, use:
# > source activate QISKitenv
#
# To deactivate this environment, use:
# > source deactivate QISKitenv
#

bash -c "source activate QISKitenv;pip install -U -r requires.txt"
Collecting IBMQuantumExperience (from -r requires.txt (line 1))
Collecting requests (from -r requires.txt (line 2))
  Using cached requests-2.18.3-py2.py3-none-any.whl
Collecting networkx (from -r requires.txt (line 3))
  Using cached networkx-1.11-py2.py3-none-any.whl
Collecting ply (from -r requires.txt (line 4))
Collecting numpy (from -r requires.txt (line 5))
  Using cached numpy-1.13.1-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting scipy (from -r requires.txt (line 6))
  Using cached scipy-0.19.1-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting matplotlib (from -r requires.txt (line 7))
  Using cached matplotlib-2.0.2-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting sphinx (from -r requires.txt (line 8))
  Using cached Sphinx-1.6.3-py2.py3-none-any.whl
Collecting idna<2.6,>=2.5 (from requests->-r requires.txt (line 2))
  Using cached idna-2.5-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests->-r requires.txt (line 2))
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests->-r requires.txt (line 2))
  Using cached certifi-2017.7.27.1-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests->-r requires.txt (line 2))
  Using cached urllib3-1.22-py2.py3-none-any.whl
Collecting decorator>=3.4.0 (from networkx->-r requires.txt (line 3))
  Using cached decorator-4.1.2-py2.py3-none-any.whl
Collecting cycler>=0.10 (from matplotlib->-r requires.txt (line 7))
  Using cached cycler-0.10.0-py2.py3-none-any.whl
Collecting pytz (from matplotlib->-r requires.txt (line 7))
  Using cached pytz-2017.2-py2.py3-none-any.whl
Collecting python-dateutil (from matplotlib->-r requires.txt (line 7))
  Using cached python_dateutil-2.6.1-py2.py3-none-any.whl
Collecting six>=1.10 (from matplotlib->-r requires.txt (line 7))
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=1.5.6 (from matplotlib->-r requires.txt (line 7))
  Using cached pyparsing-2.2.0-py2.py3-none-any.whl
Collecting Jinja2>=2.3 (from sphinx->-r requires.txt (line 8))
  Using cached Jinja2-2.9.6-py2.py3-none-any.whl
Collecting alabaster<0.8,>=0.7 (from sphinx->-r requires.txt (line 8))
  Using cached alabaster-0.7.10-py2.py3-none-any.whl
Collecting babel!=2.0,>=1.3 (from sphinx->-r requires.txt (line 8))
  Using cached Babel-2.4.0-py2.py3-none-any.whl
Collecting Pygments>=2.0 (from sphinx->-r requires.txt (line 8))
  Using cached Pygments-2.2.0-py2.py3-none-any.whl
Collecting docutils>=0.11 (from sphinx->-r requires.txt (line 8))
  Using cached docutils-0.14-py3-none-any.whl
Collecting snowballstemmer>=1.1 (from sphinx->-r requires.txt (line 8))
  Using cached snowballstemmer-1.2.1-py2.py3-none-any.whl
Collecting imagesize (from sphinx->-r requires.txt (line 8))
  Using cached imagesize-0.7.1-py2.py3-none-any.whl
Collecting sphinxcontrib-websupport (from sphinx->-r requires.txt (line 8))
  Using cached sphinxcontrib_websupport-1.0.1-py2.py3-none-any.whl
Collecting setuptools (from sphinx->-r requires.txt (line 8))
  Using cached setuptools-36.2.7-py2.py3-none-any.whl
Collecting MarkupSafe>=0.23 (from Jinja2>=2.3->sphinx->-r requires.txt (line 8))
Installing collected packages: idna, chardet, certifi, urllib3, requests, IBMQuantumExperience, decorator, networkx, ply, numpy, scipy, six, cycler, pytz, python-dateutil, pyparsing, matplotlib, MarkupSafe, Jinja2, alabaster, babel, Pygments, docutils, snowballstemmer, imagesize, sphinxcontrib-websupport, setuptools, sphinx
  Found existing installation: setuptools 27.2.0
    Uninstalling setuptools-27.2.0:
      Successfully uninstalled setuptools-27.2.0
Successfully installed IBMQuantumExperience-1.8 Jinja2-2.9.6 MarkupSafe-1.0 Pygments-2.2.0 alabaster-0.7.10 babel-2.4.0 certifi-2017.7.27.1 chardet-3.0.4 cycler-0.10.0 decorator-4.1.2 docutils-0.14 idna-2.5 imagesize-0.7.1 matplotlib-2.0.2 networkx-1.11 numpy-1.13.1 ply-3.10 pyparsing-2.2.0 python-dateutil-2.6.1 pytz-2017.2 requests-2.18.3 scipy-0.19.1 setuptools-36.2.7 six-1.10.0 snowballstemmer-1.2.1 sphinx-1.6.3 sphinxcontrib-websupport-1.0.1 urllib3-1.22
Traceback (most recent call last):
  File "/Users/sgeron/anaconda/envs/QISKitenv/bin/pip", line 6, in <module>
    sys.exit(pip.main())
  File "/Users/sgeron/anaconda/envs/QISKitenv/lib/python3.6/site-packages/pip/__init__.py", line 249, in main
    return command.main(cmd_args)
  File "/Users/sgeron/anaconda/envs/QISKitenv/lib/python3.6/site-packages/pip/basecommand.py", line 252, in main
    pip_version_check(session)
  File "/Users/sgeron/anaconda/envs/QISKitenv/lib/python3.6/site-packages/pip/utils/outdated.py", line 102, in pip_version_check
    installed_version = get_installed_version("pip")
  File "/Users/sgeron/anaconda/envs/QISKitenv/lib/python3.6/site-packages/pip/utils/__init__.py", line 838, in get_installed_version
    working_set = pkg_resources.WorkingSet()
  File "/Users/sgeron/anaconda/envs/QISKitenv/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 644, in __init__
    self.add_entry(entry)
  File "/Users/sgeron/anaconda/envs/QISKitenv/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 700, in add_entry
    for dist in find_distributions(entry, True):
  File "/Users/sgeron/anaconda/envs/QISKitenv/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1949, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File "/Users/sgeron/anaconda/envs/QISKitenv/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1463, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "/Users/sgeron/anaconda/envs/QISKitenv/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1823, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "/Users/sgeron/anaconda/envs/QISKitenv/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1703, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "/Users/sgeron/anaconda/envs/QISKitenv/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1643, in load
    mtime = os.stat(path).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sgeron/anaconda/envs/QISKitenv/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg'
make: *** [env] Error 1

--------------------------------

**Comment by sgeron** [comment]
Thanks @ewinston !

But I still get the error message below when doing "make env":

FileNotFoundError: [Errno 2] No such file or directory: '/Users/sgeron/anaconda/envs/QISKitenv/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg'
make: *** [env] Error 1

**See previous comment for full detail.**

**Comment by ewinston** [comment]
@sgeron I believe the error you are encountering is related to having two versions of setuptools in your environment (see 'conda list'). Have you tried starting with a fresh environment? If not try,
> conda remove -n QISKitenv --all

**Comment by sgeron** [comment]
@ewinston: **conda list** showed many packages installed including **setuptools**:

**setuptools                27.2.0                   py36_0**  

I used the **conda remove** command. The QISKitenv directory was well erased. **conda list** still showed the same setuptools installed.

Then the make env command gave the exact same error: 

sgeron@freifmac0033643:~/AnacondaProjects/qiskit-sdk-py$ make env
conda create -y -n QISKitenv python=3
Fetching package metadata .........
Solving package specifications: .

Package plan for installation in environment /Users/sgeron/anaconda/envs/QISKitenv:

The following NEW packages will be INSTALLED:

    openssl:    1.0.2l-0     
    pip:        9.0.1-py36_1 
    python:     3.6.2-0      
    readline:   6.2-2        
    setuptools: 27.2.0-py36_0
    sqlite:     3.13.0-0     
    tk:         8.5.18-0     
    wheel:      0.29.0-py36_0
    xz:         5.2.2-1      
    zlib:       1.2.8-3      


 To activate this environment, use:
 > source activate QISKitenv

 To deactivate this environment, use:
 > source deactivate QISKitenv

bash -c "source activate QISKitenv;pip install -U -r requires.txt"
Collecting IBMQuantumExperience (from -r requires.txt (line 1))
Collecting requests (from -r requires.txt (line 2))
  Using cached requests-2.18.3-py2.py3-none-any.whl
Collecting networkx (from -r requires.txt (line 3))
  Using cached networkx-1.11-py2.py3-none-any.whl
Collecting ply (from -r requires.txt (line 4))
Collecting numpy (from -r requires.txt (line 5))
  Using cached numpy-1.13.1-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting scipy (from -r requires.txt (line 6))
  Using cached scipy-0.19.1-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting matplotlib (from -r requires.txt (line 7))
  Using cached matplotlib-2.0.2-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting sphinx (from -r requires.txt (line 8))
  Using cached Sphinx-1.6.3-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests->-r requires.txt (line 2))
  Using cached urllib3-1.22-py2.py3-none-any.whl
Collecting idna<2.6,>=2.5 (from requests->-r requires.txt (line 2))
  Using cached idna-2.5-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests->-r requires.txt (line 2))
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests->-r requires.txt (line 2))
  Using cached certifi-2017.7.27.1-py2.py3-none-any.whl
Collecting decorator>=3.4.0 (from networkx->-r requires.txt (line 3))
  Using cached decorator-4.1.2-py2.py3-none-any.whl
Collecting pytz (from matplotlib->-r requires.txt (line 7))
  Using cached pytz-2017.2-py2.py3-none-any.whl
Collecting python-dateutil (from matplotlib->-r requires.txt (line 7))
  Using cached python_dateutil-2.6.1-py2.py3-none-any.whl
Collecting six>=1.10 (from matplotlib->-r requires.txt (line 7))
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=1.5.6 (from matplotlib->-r requires.txt (line 7))
  Using cached pyparsing-2.2.0-py2.py3-none-any.whl
Collecting cycler>=0.10 (from matplotlib->-r requires.txt (line 7))
  Using cached cycler-0.10.0-py2.py3-none-any.whl
Collecting Jinja2>=2.3 (from sphinx->-r requires.txt (line 8))
  Using cached Jinja2-2.9.6-py2.py3-none-any.whl
Collecting setuptools (from sphinx->-r requires.txt (line 8))
  Using cached setuptools-36.2.7-py2.py3-none-any.whl
Collecting Pygments>=2.0 (from sphinx->-r requires.txt (line 8))
  Using cached Pygments-2.2.0-py2.py3-none-any.whl
Collecting babel!=2.0,>=1.3 (from sphinx->-r requires.txt (line 8))
  Using cached Babel-2.4.0-py2.py3-none-any.whl
Collecting imagesize (from sphinx->-r requires.txt (line 8))
  Using cached imagesize-0.7.1-py2.py3-none-any.whl
Collecting sphinxcontrib-websupport (from sphinx->-r requires.txt (line 8))
  Using cached sphinxcontrib_websupport-1.0.1-py2.py3-none-any.whl
Collecting snowballstemmer>=1.1 (from sphinx->-r requires.txt (line 8))
  Using cached snowballstemmer-1.2.1-py2.py3-none-any.whl
Collecting alabaster<0.8,>=0.7 (from sphinx->-r requires.txt (line 8))
  Using cached alabaster-0.7.10-py2.py3-none-any.whl
Collecting docutils>=0.11 (from sphinx->-r requires.txt (line 8))
  Using cached docutils-0.14-py3-none-any.whl
Collecting MarkupSafe>=0.23 (from Jinja2>=2.3->sphinx->-r requires.txt (line 8))
Installing collected packages: urllib3, idna, chardet, certifi, requests, IBMQuantumExperience, decorator, networkx, ply, numpy, scipy, pytz, six, python-dateutil, pyparsing, cycler, matplotlib, MarkupSafe, Jinja2, setuptools, Pygments, babel, imagesize, sphinxcontrib-websupport, snowballstemmer, alabaster, docutils, sphinx
  Found existing installation: setuptools 27.2.0
    Uninstalling setuptools-27.2.0:
      Successfully uninstalled setuptools-27.2.0
Successfully installed IBMQuantumExperience-1.8 Jinja2-2.9.6 MarkupSafe-1.0 Pygments-2.2.0 alabaster-0.7.10 babel-2.4.0 certifi-2017.7.27.1 chardet-3.0.4 cycler-0.10.0 decorator-4.1.2 docutils-0.14 idna-2.5 imagesize-0.7.1 matplotlib-2.0.2 networkx-1.11 numpy-1.13.1 ply-3.10 pyparsing-2.2.0 python-dateutil-2.6.1 pytz-2017.2 requests-2.18.3 scipy-0.19.1 setuptools-36.2.7 six-1.10.0 snowballstemmer-1.2.1 sphinx-1.6.3 sphinxcontrib-websupport-1.0.1 urllib3-1.22
Traceback (most recent call last):
  File "/Users/sgeron/anaconda/envs/QISKitenv/bin/pip", line 6, in <module>
    sys.exit(pip.main())
  File "/Users/sgeron/anaconda/envs/QISKitenv/lib/python3.6/site-packages/pip/__init__.py", line 249, in main
    return command.main(cmd_args)
  File "/Users/sgeron/anaconda/envs/QISKitenv/lib/python3.6/site-packages/pip/basecommand.py", line 252, in main
    pip_version_check(session)
  File "/Users/sgeron/anaconda/envs/QISKitenv/lib/python3.6/site-packages/pip/utils/outdated.py", line 102, in pip_version_check
    installed_version = get_installed_version("pip")
  File "/Users/sgeron/anaconda/envs/QISKitenv/lib/python3.6/site-packages/pip/utils/__init__.py", line 838, in get_installed_version
    working_set = pkg_resources.WorkingSet()
  File "/Users/sgeron/anaconda/envs/QISKitenv/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 644, in __init__
    self.add_entry(entry)
  File "/Users/sgeron/anaconda/envs/QISKitenv/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 700, in add_entry
    for dist in find_distributions(entry, True):
  File "/Users/sgeron/anaconda/envs/QISKitenv/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1949, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File "/Users/sgeron/anaconda/envs/QISKitenv/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1463, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "/Users/sgeron/anaconda/envs/QISKitenv/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1823, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "/Users/sgeron/anaconda/envs/QISKitenv/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1703, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "/Users/sgeron/anaconda/envs/QISKitenv/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1643, in load
    mtime = os.stat(path).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sgeron/anaconda/envs/QISKitenv/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg'
make: *** [env] Error 1
sgeron@freifmac0033643:~/AnacondaProjects/qiskit-sdk-py$

**Comment by ewinston** [comment]
Hi @sgeron,
It looks like you might not be using the commit I did to correct this issue. It's on the latest dev branch. If you want to set it up manually do (after removing QISKitenv) in the same directory as the Makefile,

> conda create -y -n QISKitenv python=3
> source activate QISKitenv
> pip install -r requires.txt

**Comment by sgeron** [comment]
Hi @ewinston, thanks, I did that and it installed properly.

**During the installation, the following positive message:**
Successfully installed IBMQuantumExperience-1.8 Jinja2-2.9.6 MarkupSafe-1.0 Pygments-2.2.0 alabaster-0.7.10 babel-2.4.0 certifi-2017.7.27.1 chardet-3.0.4 cycler-0.10.0 decorator-4.1.2 docutils-0.14 idna-2.5 imagesize-0.7.1 matplotlib-2.0.2 networkx-1.11 numpy-1.13.1 ply-3.10 pyparsing-2.2.0 python-dateutil-2.6.1 pytz-2017.2 requests-2.18.3 scipy-0.19.1 six-1.10.0 snowballstemmer-1.2.1 sphinx-1.6.3 sphinxcontrib-websupport-1.0.1 urllib3-1.22

Then, I launched the jupyter notebook and the previous error returned: **ModuleNotFoundError: No module named 'IBMQuantumExperience'**

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-6-a1863900cb66> in <module>()
      9 from pprint import pprint
     10 
---> 11 from qiskit import QuantumProgram
     12 import Qconfig

/Users/sgeron/AnacondaProjects/qiskit-sdk-py/qiskit/__init__.py in <module>()
      8 from ._qiskiterror import QISKitError
      9 import qiskit.extensions.standard
---> 10 from ._quantumprogram import QuantumProgram
     11 from ._quantumprogram import Result
     12 #from .simulators import UnitarySimulator

/Users/sgeron/AnacondaProjects/qiskit-sdk-py/qiskit/_quantumprogram.py in <module>()
     30 
     31 # use the external IBMQuantumExperience Library
---> 32 from IBMQuantumExperience.IBMQuantumExperience import IBMQuantumExperience
     33 
     34 # Stable Modules

**ModuleNotFoundError: No module named 'IBMQuantumExperience'**

**Comment by rraymondhp** [comment]
Hi, 
This can be cause by jupyter notebook running different env than what you started with the terminal. A similar issue was discussed here: 
https://stackoverflow.com/questions/37891550/jupyter-notebook-running-kernel-in-different-env

**Comment by sgeron** [comment]
Bravo!
This solved the matter:
conda create -y -n QISKitenv python=3 jupyter
