### ISSUE TITLE
Unexpected result qasm simulator with coupling map (stable) 

### ISSUE THREAD

**Issue by adjs** [QISKit/qiskit-sdk-py#181]
I believe that I found a bug at stable (see 2 below). I have two enhancement suggestions (see 1 and 3).

## Expected Behavior
Expected result
'{'1000': 50}'

## Current Behavior
Result qasm simulator without coupling map and initial layout
{'1000': 50}

Result qasm simulator with coupling map and initial layout
{'1000': 25, '0000': 25}

Result ibmqx5
{"error":{"status":400,"message":"Error parsing QASM. Error parsing qasm number 0. Gates after a measure are blocked","code":"QASM_NOT_VALID"}}

## Steps to Reproduce (for bugs)

Attached [file](https://github.com/QISKit/qiskit-sdk-py/files/1540826/recover.py.txt)

## Context

1. In [arXiv:quant-ph/0012100] a probabilistic quantum memory is defined. Given a memory $|m\rangle = \frac{1}{\sqrt{k}} |p_k\rangle$ and an input $|i\rangle$ the memory outputs 0 with probability $p(0) = \frac{1}{k} cos^2(\frac{\pi}{2n} d_H(i,p_k))$ and 1 with probability $1 – p0$.

After see  #152, I am working on the implementation of the retrieval algorithm of [arXiv:quant-ph/0012100]. 

Is this a viable enhancement?

2. Different behavior when I compile with or without coupling_map. Error when I run with backend ibmqx5

I got strange results when I finished the implementation (attached file). With memory |000\rangle and input |111\rangle I obtained different results using qasm simulator without coupling map and qasm simulator with coupling map.

A running example.
Expected result
'{'1000': 50}'

Result qasm simulator without coupling map and initial layout
{'1000': 50}

Result qasm simulator with coupling map and initial layout
{'1000': 25, '0000': 25}

Result ibmqx5
{"error":{"status":400,"message":"Error parsing QASM. Error parsing qasm number 0. Gates after a measure are blocked","code":"QASM_NOT_VALID"}}

3. Initial layout
 I compile without an initial_layout.  After a  compilation, I get the final layout (I didn't verify the generated layout) and use as initial layout in the next shots. In some executions the mapper failed. I believe that the initial layout is not being verified. Could the mapper verify the initial layout?

## some logs

/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 /Users/adeniltonsilva/Documents/GitHub/qiskit-sdk-py/probabilistic_memory_ibmqx.py
Expected result
'{'1000': 50}'
Result qasm simulator without coupling map and initial layout
{'1000': 50}
pre-mapping properties: {'size': 51, 'depth': 23, 'width': 7, 'bits': 4, 'factors': 1, 'operations': {'u2': 2, 'u1': 12, 'u3': 21, 'cx': 12, 'measure': 4}}
initial layout: {('p', 0): ('q', 1), ('p', 1): ('q', 0), ('p', 2): ('q', 2), ('m', 0): ('q', 3), ('m', 1): ('q', 4), ('m', 2): ('q', 14), ('c', 0): ('q', 5)}
final layout: {('p', 0): ('q', 1), ('p', 1): ('q', 0), ('p', 2): ('q', 2), ('m', 0): ('q', 3), ('m', 1): ('q', 4), ('m', 2): ('q', 14), ('c', 0): ('q', 5)}
post-mapping properties: {'size': 155, 'depth': 71, 'width': 15, 'bits': 4, 'factors': 9, 'operations': {'u1': 9, 'cx': 60, 'u2': 78, 'u3': 4, 'measure': 4}}
running on backend: local_qasm_simulator
Result qasm simulator with coupling map and initial layout
{'1000': 25, '0000': 25}
pre-mapping properties: {'size': 51, 'depth': 23, 'width': 7, 'bits': 4, 'factors': 1, 'operations': {'u2': 2, 'u1': 12, 'u3': 21, 'cx': 12, 'measure': 4}}
initial layout: {('p', 0): ('q', 1), ('p', 1): ('q', 0), ('p', 2): ('q', 2), ('m', 0): ('q', 3), ('m', 1): ('q', 4), ('m', 2): ('q', 14), ('c', 0): ('q', 5)}
Traceback (most recent call last):
  File "/Users/adeniltonsilva/Documents/GitHub/qiskit-sdk-py/probabilistic_memory_ibmqx.py", line 129, in <module>
    timeout=240, silent=False)
  File "/Users/adeniltonsilva/Documents/GitHub/qiskit-sdk-py/qiskit/_quantumprogram.py", line 1184, in execute
    max_credits=max_credits, seed=seed)
  File "/Users/adeniltonsilva/Documents/GitHub/qiskit-sdk-py/qiskit/_quantumprogram.py", line 854, in compile
    dag_circuit, coupling, initial_layout, trials=20, verbose=False)
  File "/Users/adeniltonsilva/Documents/GitHub/qiskit-sdk-py/qiskit/mapper/_mapping.py", line 425, in swap_mapper
    aliases=layout))
qiskit.mapper._mappererror.MapperError: 'swap_mapper failed: layer 17, sublayer 1, "cx q[0],q[14];\n"'

Process finished with exit code 1

/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 /Users/adeniltonsilva/Documents/GitHub/qiskit-sdk-py/probabilistic_memory_ibmqx.py
Expected result
'{'1000': 50}'
Result qasm simulator without coupling map and initial layout
{'1000': 50}
pre-mapping properties: {'size': 51, 'depth': 23, 'width': 7, 'bits': 4, 'factors': 1, 'operations': {'u2': 2, 'u1': 12, 'u3': 21, 'cx': 12, 'measure': 4}}
initial layout: {('p', 0): ('q', 1), ('p', 1): ('q', 0), ('p', 2): ('q', 2), ('m', 0): ('q', 3), ('m', 1): ('q', 4), ('m', 2): ('q', 14), ('c', 0): ('q', 5)}
Traceback (most recent call last):
  File "/Users/adeniltonsilva/Documents/GitHub/qiskit-sdk-py/probabilistic_memory_ibmqx.py", line 121, in <module>
    timeout=240, silent=False)
  File "/Users/adeniltonsilva/Documents/GitHub/qiskit-sdk-py/qiskit/_quantumprogram.py", line 1184, in execute
    max_credits=max_credits, seed=seed)
  File "/Users/adeniltonsilva/Documents/GitHub/qiskit-sdk-py/qiskit/_quantumprogram.py", line 854, in compile
    dag_circuit, coupling, initial_layout, trials=20, verbose=False)
  File "/Users/adeniltonsilva/Documents/GitHub/qiskit-sdk-py/qiskit/mapper/_mapping.py", line 425, in swap_mapper
    aliases=layout))
qiskit.mapper._mappererror.MapperError: 'swap_mapper failed: layer 1, sublayer 3, "cx q[0],q[14];\n"'

Process finished with exit code 1

Result ibmqx5
/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 /Users/adeniltonsilva/Documents/GitHub/qiskit-sdk-py/probabilistic_memory_ibmqx.py
pre-mapping properties: {'size': 51, 'depth': 23, 'width': 9, 'bits': 4, 'factors': 3, 'operations': {'u2': 2, 'u1': 12, 'u3': 21, 'cx': 12, 'measure': 4}}
initial layout: {('p', 0): ('q', 1), ('p', 1): ('q', 0), ('p', 2): ('q', 2), ('m', 0): ('q', 3), ('m', 1): ('q', 4), ('m', 2): ('q', 14), ('u', 0): ('q', 5), ('u', 1): ('q', 6), ('c', 0): ('q', 7)}
final layout: {('p', 0): ('q', 1), ('p', 1): ('q', 0), ('p', 2): ('q', 2), ('m', 0): ('q', 3), ('m', 1): ('q', 4), ('m', 2): ('q', 14), ('u', 0): ('q', 5), ('u', 1): ('q', 6), ('c', 0): ('q', 7)}
post-mapping properties: {'size': 205, 'depth': 90, 'width': 15, 'bits': 4, 'factors': 7, 'operations': {'u1': 12, 'cx': 84, 'u2': 105, 'measure': 4}}
running on backend: ibmqx5
WARNING:IBMQuantumExperience.IBMQuantumExperience:Got a 400 code response to https://quantumexperience.ng.bluemix.net/api/Jobs?access_token=HCBtEwhZZBdQNHpxlHlO9yCSwrxwU0KHAdlcVQzwiYfnKKmmA0dwd7m4SiqAvVaT: {"error":{"status":400,"message":"Error parsing QASM. Error parsing qasm number 0. Gates after a measure are blocked","code":"QASM_NOT_VALID"}}
WARNING:IBMQuantumExperience.IBMQuantumExperience:Got a 400 code response to https://quantumexperience.ng.bluemix.net/api/Jobs?access_token=HCBtEwhZZBdQNHpxlHlO9yCSwrxwU0KHAdlcVQzwiYfnKKmmA0dwd7m4SiqAvVaT: {"error":{"status":400,"message":"Error parsing QASM. Error parsing qasm number 0. Gates after a measure are blocked","code":"QASM_NOT_VALID"}}
WARNING:IBMQuantumExperience.IBMQuantumExperience:Got a 400 code response to https://quantumexperience.ng.bluemix.net/api/Jobs?access_token=HCBtEwhZZBdQNHpxlHlO9yCSwrxwU0KHAdlcVQzwiYfnKKmmA0dwd7m4SiqAvVaT: {"error":{"status":400,"message":"Error parsing QASM. Error parsing qasm number 0. Gates after a measure are blocked","code":"QASM_NOT_VALID"}}
WARNING:IBMQuantumExperience.IBMQuantumExperience:Got a 400 code response to https://quantumexperience.ng.bluemix.net/api/Jobs?access_token=HCBtEwhZZBdQNHpxlHlO9yCSwrxwU0KHAdlcVQzwiYfnKKmmA0dwd7m4SiqAvVaT: {"error":{"status":400,"message":"Error parsing QASM. Error parsing qasm number 0. Gates after a measure are blocked","code":"QASM_NOT_VALID"}}
WARNING:IBMQuantumExperience.IBMQuantumExperience:Got a 400 code response to https://quantumexperience.ng.bluemix.net/api/Jobs?access_token=HCBtEwhZZBdQNHpxlHlO9yCSwrxwU0KHAdlcVQzwiYfnKKmmA0dwd7m4SiqAvVaT: {"error":{"status":400,"message":"Error parsing QASM. Error parsing qasm number 0. Gates after a measure are blocked","code":"QASM_NOT_VALID"}}
Traceback (most recent call last):
  File "/Users/adeniltonsilva/Documents/GitHub/qiskit-sdk-py/probabilistic_memory_ibmqx.py", line 206, in <module>
    timeout=240, silent=False)
  File "/Users/adeniltonsilva/Documents/GitHub/qiskit-sdk-py/qiskit/_quantumprogram.py", line 1185, in execute
    result = self.run(qobj, wait=wait, timeout=timeout, silent=silent)
  File "/Users/adeniltonsilva/Documents/GitHub/qiskit-sdk-py/qiskit/_quantumprogram.py", line 1030, in run
    raise ResultError(output['error'])
qiskit._quantumprogram.ResultError: 'Error parsing QASM. Error parsing qasm number 0. Gates after a measure are blocked'

Process finished with exit code 1

## Your Environment

* Version used: stable
* Environment name and version (e.g. Python 3.6.1):
* Operating System and version: macOs 10.13.1

**Comment by ajavadia** [comment]
@adjs is this still a bug? I wanted to try and reproduce it after recent changes to stable, but the attached file does not open anymore. If it is still a bug, please reopen the issue with a code example. Thansk!
