### ISSUE TITLE
Behavior of the instruction "measure q[i] -> q[j];"

### ISSUE THREAD

**Issue by ChristopheVuillot** [QISKit/qiskit-sdk-py#2]
The QASM instruction "measure q[k1] -> q[k2];" with k1 and k2 different integers is not done properly on the real device (when called via run_job).
It behaves as if it were "measure q[k1] -> q[k1];" whatever k2 is.

**Comment by jaygambetta** [comment]
Thanks this is a problem and we are working on fixing it. In simulation i think it works fine but the hardware we are working on it.

**Comment by lbello** [comment]
This is a limitation of the current architecture backend and depends on the release of 0.5, when qobj is integrated. Therefore, I'm tagging this issue with "on hold".
