### ISSUE TITLE
Installing through Python Package

### ISSUE THREAD

**Issue by rasa97** [QISKit/qiskit-sdk-py#204]
I am working on Mac which has both python 2 & 3 version. I had to install qiskit using the pip3 command; contrary to the docs which have the simple pip command. Shouldn't that be changed to `pip3 install qiskit`

**Comment by ewinston** [comment]
The installation instructions have you install pip in your `QISKitenv` python3 conda environment where it should appear as `pip`. Try typing `type pip` to see which pip you are executing. What you're describing has happened to me if I forget to activate my conda environment in which case pip is taken from my OS distribution.
