### ISSUE TITLE
Create tests for qiskit.tools package.

### ISSUE THREAD

**Issue by atilag** [QISKit/qiskit-sdk-py#221]
We don't have tests for all the great stuff we have in `qiskit.tools`. 
We need to address this ASAP :)

Probably the entire package needs a relocation/restructuring into the SDK, but let's discuss this in another thread.

**Comment by lbello** [comment]
Currently, this is a coverage information of the files in `qiskit/tools`:

Module | statements | missing | coverage
-- | -- | --| --
qiskit/tools/apps/fermion.py | 173 | 173 | 0%
qiskit/tools/qcvv/fitters.py | 49 | 49 | 0%
qiskit/tools/visualization.py | 825 | 817 | 1%
qiskit/tools/apps/optimization.py | 240 | 171 | 29%
qiskit/tools/qi/qi.py | 207 | 99 | 52%
qiskit/tools/qi/pauli.py | 155 | 38 | 75%
qiskit/tools/qcvv/tomography.py | 310 | 74 | 76%
qiskit/tools/file_io.py | 86 | 17 | 80%

Shall we open individual issues for `fermion` (@amezzac), `qcvv` (@chriseclectic), `visualization`, `optimization`(@amezzac), and`qi` (@chriseclectic)?

**Comment by 1ucian0** [comment]
I just noticed that `matplotlib` on MacOS is hell, so the numbers for `visualization` are off. The rest should be correct.

**Comment by 1ucian0** [comment]
Individual issues created. The file location structure is been discussed in #268
