### ISSUE TITLE
no hpc parameter in run_job

### ISSUE THREAD

**Issue by ajavadia** [QISKit/qiskit-sdk-py#228]
In PR #216, @atilag modified `_qeremote.py` to add an hpc parameter to the `run_job` function. This throws an error since the function signature does not have this argument.

I think perhaps the fix should be applied to the API repository, but I'm raising the issue here since this is where errors occur.

## Expected Behavior

Function signature must match use case.

## Steps to Reproduce (for bugs)

1. The last cell in the getting_started Jupyter tutorial.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 3.6.1):
* Operating System and version:

**Comment by lbello** [comment]
You can update IBMQuantumExperience with 
`pip install IBMQuantumExperience --upgrade`

This issue should be solved in `IBMQuantumExperience-1.8.25`.

In the future, we should be more careful with userland. It looks like the IBMQuantumExperience changed the interface in a minor upgrade.
