### ISSUE TITLE
Circuit Graph in local

### ISSUE THREAD

**Issue by ismaelfaro** [QISKit/qiskit-sdk-py#235]
Create the Circuit Graph representation in local mode.

## Current Behavior & Expected Behavior 
Now the Circuit Graph from the QASM/Qobj is generated via IBM Q Experience API, the idea is move part of this graph generation into the local functions. 

## Possible Solution
use the Python graphic library to done it, one very standard option is Pillow library.

**Comment by ajavadia** [comment]
@ismaelfaro: I spent a lot of time thinking about how to do this (especially for Jupyter tutorials). In the end the best solution I could find was to use local installations of `pdflatex` and the [`pdf2image` Python package](https://github.com/Belval/pdf2image) (which is a wrapper around Pillow). 

I wrote this in the `circuitImage` function in [this tutorial notebook](https://github.com/ajavadia/qiskit-tutorial/blob/master/1_introduction/getting_started.ipynb).

Is this an acceptable solution, or do you think it can be done with fewer dependencies?

**Comment by diego-plan9** [comment]
Closed by #295 - and followed-up by #311!
