### ISSUE TITLE
Error in tomography.py

### ISSUE THREAD

**Issue by ajavadia** [QISKit/qiskit-sdk-py#236]
The following functions in `qiskit/tools/qcvv/tomography.py` throw an error [lines 920-989]:
* `build_state_tomography_circuits`
* `build_process_tomography_circuits`
* `state_tomography_circuit_names`
* `process_tomography_circuit_names`
* `state_tomography_data`
* `process_tomography_data`

## Possible Solution

I believe the source of the error comes from 'pauli' being written in lower case in these functions' arguments, while on `line 333` we check for 'Pauli' (upper case).
So to fix, make all function arguments into 'Pauli'.

## Steps to Reproduce (for bugs)

I encountered this error while running the following tutorials:
* state_tomography
* process_tomography
* wigner_functions
(The above functions are in fact deprecated, and are kept only for compatibility with these tutorials. So while fixing this, can we also update the tutorial?)

## Your Environment

* Version used:
* Environment name and version (e.g. Python 3.6.1):
* Operating System and version:

**Comment by chriseclectic** [comment]
@ajavadia Yes, those tutorials need updating! Just to confirm: is the error only in the tutorials, not the functions themselves?

I suppose we could also add a `str.lower()` to the function defs so capitalisation doesn't matter.

**Comment by ajavadia** [comment]
Hi @chriseclectic, no the bug is in the functions. The functions will throw an error whenever they are called. It just happens that the tutorials call them.

The fix is just to convert all the `meas_basis='pauli'` to `meas_basis='Pauli'` in function definitions. I'm just saying since those are deprecated functions, you may want to not use them in the tutorials at all. But this fix will stop errors for now.

**Comment by ajavadia** [comment]
Thanks for PR#237! The tutorials work now. Closing this issue.
