### ISSUE TITLE
Drawing gates with familiar names

### ISSUE THREAD

**Issue by rraymondhp** [QISKit/qiskit-sdk-py#246]
I have tried drawing gates with the latex_drawer function. It draws familiar gates (H, X, Y, Z) etc with `u3` gates instead of the familiar gate symbols. 
## Current Behavior

The QASM is written as below, but the figure obtained uses `u3` as attached. 
```
h qr[0];
h qr[1];
h qr[2];
h qr[3];
x qr[4];
h qr[4];
```
[bv.pdf](https://github.com/QISKit/qiskit-sdk-py/files/1625174/bv.pdf)

## Possible Solution

When adding circuits like below, the corresponding gates drawn should use the symbols corresponding to the command. 
```
```

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 3.6.1):
* Operating System and version:

**Comment by awcross1** [comment]
hi @rraymondhp the signature of the drawing method is:
def latex_drawer(circuit, filename=None, basis="u1,u2,u3,cx")
I think you can change the optional "basis" parameter. Does that work?

**Comment by rraymondhp** [comment]
I think this should be closed cause can be handled by passing the argument as pointed out.
