### ISSUE TITLE
Running a .json on cpp-simulator throws an iostream error

### ISSUE THREAD

**Issue by vtomole** [QISKit/qiskit-sdk-py#260]
I built the latest cpp simulator on my computer and it can't run any programs because it throws an error.

## Expected Behavior
The cpp simulator should run my QASM program; but it isn't.

## Current Behavior
```
vtomole@vtomole:~/qiskit-sdk-py/out$ ./qiskit_simulator test_load.json
{
    "status": "ERROR: Invalid input (basic_ios::clear: iostream error)",
    "success": false
}

```

## Steps to Reproduce (for bugs):

contents of test_load.json:
```
{
    "circuitName": {
        "qasm": "OPENQASM 2.0;\ninclude \"qelib1.inc\";\nqreg qname[3];\ncreg cname[3];\nu3(0.300000000000000,0.200000000000000,0.100000000000000) qname[0];\nh qname[1];\ncx qname[1],qname[2];\nbarrier qname[0],qname[1],qname[2];\ncx qname[0],qname[1];\nh qname[0];\nif(cname==1) z qname[2];\nif(cname==1) x qname[2];\nmeasure qname[0] -> cname[0];\nmeasure qname[1] -> cname[1];\n"
    }
}
```

## Your Environment
* GCC: gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5)
* Clang: clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)
* Operating System and version:  Ubuntu 16.04

**Comment by diego-plan9** [comment]
Hmmm, it is currently a bit hidden in the [simulator documentation](https://github.com/QISKit/qiskit-sdk-py/blob/master/src/cpp-simulator/README.md#running-from-the-command-line), but at the moment the simulator is meant to accept a full `QObj` as a parameter - which has a different structure than the `json` you are currently passing. The actual error (`basic_ios::clear: iostream error`) is also a bit misleading, but it seems to be related to not being able to parse the input according to what it expects.

We are actually working on a clearer definition of the `QObj`, but in the meantime, it might help to check what is passed to the simulator [here](https://github.com/QISKit/qiskit-sdk-py/blob/master/qiskit/backends/_qiskit_cpp_simulator.py#L155). Would this be useful to your needs? Depending on your use case, it might also be worth considering using the existing functionality to generate the JSON, which you can then use indepently, using a variation of:

```python
import qiskit

qp = qiskit.QuantumProgram()
qp.load_qasm_file('my_qasm_file.qasm')
my_qobj = qp.compile('my_qasm_file', 'local_qiskit_simulator')
with open('myson.json', 'w') as outfile:
    json.dump(my_qobj, outfile)
```

And then use `myjson.json` as input when running the simulator manually.

**Comment by atilag** [comment]
@vtomole I'm closing this issue per @diego-plan9 explanation. Anyway, if you feel that we should reopen it, ping me and I will do so.

**Comment by yaelbh** [comment]
I also noticed that. Commenting the line
ifile.exceptions(std::ifstream::failbit | std::ifstream::badbit);
solved it for me.
