### ISSUE TITLE
add qiskit.backend methods for getting parameter and calibration data

### ISSUE THREAD

**Issue by ewinston** [QISKit/qiskit-sdk-py#262]
Add methods to qiskit.backends for getting parameters and calibration data.

## Current Behavior
Currently the way to obtain backend parameters and calibration is through QuantumProgram methods. These could be moved to qiskit.backends.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 3.6.1):
* Operating System and version:

**Comment by diego-plan9** [comment]
Good idea, it feels more natural for those methods to be part of `qiskit.backends`. In the same spirit, perhaps we can take the chance to also revise the way the backends are handled as a whole in `QuantumProgram`? At the moment there is some overlap between the `Qp.__ONLINE_BACKENDS` / `Qp.__LOCAL_BACKENDS` class variables (with the methods that modify and use them) and the `qiskit.backends` machinery.

**Comment by jaygambetta** [comment]
I agree completly. Lets start removing from quantum program (slowly with a few versions).
