### ISSUE TITLE
Fail to compile cpp-simulator in Windows 7 environment

### ISSUE THREAD

**Issue by itoko** [QISKit/qiskit-sdk-py#265]
Fail to compile cpp-simulator (qiskit_simulator) with g++ (GCC) 6.4.0 on Windows 7 (Cygwin 64bit).

## Possible Solution
Add the following lines in the head of simulator.hpp
```
#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif
```

**Comment by atilag** [comment]
Hi @itoko , I'm working on some stuff for QISKit that will add Windows support among other cool things ;)... I already have a Win64 executable with all it's dependencies in a package, just in case you need the Windows simulator right now, and cannot wait until my changes are merged (very soon I hope!).

**Comment by atilag** [comment]
@itoko we have merged CMake integration in `master` branch, so anyone should be able to build the simulator on Windows. Just follow CONTRIBUTING guide steps to make the build.
I'm closing this issue, if you find problems building it with CMake, let's open a new one.
