### ISSUE TITLE
Change state fidelity convention from |<a|b>| to |<a|b>|^2

### ISSUE THREAD

**Issue by chriseclectic** [QISKit/qiskit-sdk-py#278]
Currently the `state_fidelity` function in `tools.qi.qi.py` is defined using the Nielsen and Chuang [1]  convention of 
`F(|a>,|b>) =  |<a|b>|` (for pure states). 
This should be changed by the convention more commonly used in more recent papers and by other authors (Eg. [2, 3]): 
`F(|a>,|b>) = |<a|b>|^2`.

[1] Nielsen and Chuang - Quantum Computation and Quantum Information
[2] Kitaev, Shen, and Vyalyi - Classical and Quantum Computation
[3] Schumacher and Westmoreland - Quantum Processes, Systems, & Information

**Comment by jaygambetta** [comment]
Lets change it to the square as it is the standard that many of us have been using. We should of done this the first time.
