### ISSUE TITLE
Failed building wheel for qiskit

### ISSUE THREAD

**Issue by pep3e** [QISKit/qiskit-sdk-py#292]
I am trying to install qiskit through pip on IBM DSX (Data science experience). Running Python 3.5 with Spark 2.1 Notebook.
Following the steps on the QISKit main page ( https://www.qiskit.org/ ) and here in this paper - https://nbviewer.jupyter.org/github/QISKit/qiskit-tutorial/blob/stable/1_introduction/running_on_IBM_DSX.ipynb

I always get to the point where I need to install qiskit:
pip install qiskit

Every time I try the installation fails with the following error:

running install_egg_info
  Copying qiskit.egg-info to build/bdist.linux-x86_64/wheel/qiskit-_QISKIT_VERSION_.data/purelib/qiskit-_QISKIT_VERSION_-py3.5.egg-info
  error: [Errno 2] No such file or directory: 'qiskit.egg-info'
  
  ----------------------------------------
  Failed building wheel for qiskit
  Running setup.py clean for qiskit

Also tried to clone the repo and rename the install.py.in file to install.py and run pip install ./qiskit-sdk-py/install.py but the error comes up.

**Comment by diego-plan9** [comment]
Hello @pep3e ,

there were some changes in the build system for the latest 0.4.9 release that might the cause - however, I'm having some trouble reproducing the issue. Could you paste the output of these commands in your environment, to try to narrow down the issue?

```
cmake --version
pip --version
uname -a
``` 

Also, could you confirm if the following line you pasted has been copied verbatim (ie has not been modified by you when writing the issue)?
```
Copying qiskit.egg-info to build/bdist.linux-x86_64/wheel/qiskit-_QISKIT_VERSION_.data/purelib/qiskit-_QISKIT_VERSION_-py3.5.egg-info
```

The reason for asking is due to the last line of your comment - the file `setup.py.in` is not meant to be copied and renamed manually, and that copy and rename might be causing that particular error. Could you try running in a new folder:

```

**Comment by pep3e** [comment]
Hello Diego,
The problem was that I didn't have cmake:
**pip install cmake** 
fixed my issue. Thank you for the help

**Comment by diego-plan9** [comment]
Glad to hear, @pep3e ! For the record (and for reference if the same problem is encountered by other users), on the upcoming QISKit releases, `cmake` will not be required for installing via `pip` - it was a temporary byproduct of the latest changes.

**Comment by attp** [comment]
Hi @diego-plan9, I'm currently reworking the DSX install instructions and am having this problem as well. This is the error I get when I try `pip install qiskit`, even when `cmake` is available:

> running install_egg_info
>Copying qiskit.egg-info to /gpfs/fs01/user/s048-114a05d8c2ea2f-aeaae8f7ca3a/.local/lib/python3.5/site-packages/qiskit-0.4.9-py3.5.egg-info
>error: [Errno 2] No such file or directory: 'qiskit.egg-info'`

Do I need to specify a particular version of QISKit?

**Comment by atilag** [comment]
Hi @attp let me jump in with @diego-plan9 permission.
I have just uploaded a prebuilt binary package compatible with DSX. Try to install again:
```
$ pip install --no-cache-dir qiskit
```
... and let me know if somehing is wrong.

**Comment by attp** [comment]
Thanks @atilag - it works now. :)

**Comment by amantamirat** [comment]
pip install cmake ,is works fine!!! and then pip install qiskit
