### ISSUE TITLE
Qiskit 0.4.9 Docker build error

### ISSUE THREAD

**Issue by eddieschoute** [QISKit/qiskit-sdk-py#307]
Building an alpine docker image of qiskit-0.4.9 results in a build error.

## Expected Behavior
`pip install 'qiskit==0.4.9'` should succeed.

## Current Behavior
The installation fails with a build error. See the attached logfile for the output log.
[log.txt](https://github.com/QISKit/qiskit-sdk-py/files/1745836/log.txt)

Building `pip install qiskit==0.4.8` does succeed. The docker image is located at https://github.com/eddieschoute/python3-qiskit

## Possible Solution
Provide build requirements so that I can figure out what dependencies are missing.
Or output missing dependencies that cause the build to fail.

## Steps to Reproduce (for bugs)
1. `git clone https://github.com/eddieschoute/python3-qiskit.git`
2. `cd python3-qiskit`
3. make sure you are on the right commit: `git reset --hard e2f71f73e39fcfde8db43860ee305e95f1502c46`
4. `docker build .`

## Context
My CI build system relies on the docker image and I recently bumped my version to qiskit-0.4.9. The CI system is now broken.
Building locally on macOS 10.13 did succeed.

## Your Environment
* Version used: qiskit-0.4.9
* Environment name and version (e.g. Python 3.6.1): python3.6.4
* Operating System and version: Alpine Linux, docker image

**Comment by atilag** [comment]
Hi @eddieschoute,
Seems like your docker image must be missing some of the components needed to build the C++ Simulator.
Anyway, that shouldn't be a problem at all, you are actually hitting a bug that we have already [fixed](https://github.com/QISKit/qiskit-sdk-py/commit/9a101a80e49bafdc32f9677469d3aae458a4ea1f) in the master branch, so it will be fixed for the next  release, that should happen soon.
If you can install using pip in verbose mode: `pip install -vvv 'qiskit==0.4.9'` and paste the traces here, I could see what's failing on your build and try to sort it out.

**Comment by eddieschoute** [comment]
Hi @atilag , I have attached the verbose log. I don't see any trace of why the error happens but maybe you have more insight: [log-verbose.txt](https://github.com/QISKit/qiskit-sdk-py/files/1748669/log-verbose.txt)

**Comment by atilag** [comment]
@eddieschoute I just noticed that Alpine build-base package doesn't include CMake. Since 0.4.9, CMake (>=3.5) is required to build non-python code. Try to install it on your docker image, and send me the verbose log again if it fails.

**Comment by eddieschoute** [comment]
Adding CMake to the docker packages has resolved the issue.
