### ISSUE TITLE
load/save Results

### ISSUE THREAD

**Issue by ismaelfaro** [QISKit/qiskit-sdk-py#32]
We need to allow to store and load the Result like a part of the save your Quantum Program

## Expected Behavior

Every time that you use the QuantumProgram.save() and QuantumProgram.load() we need to store and load the executions results (from the offline simulator and online simulators or real chips), as part of the our QP file.
 
## Current Behavior

Currently only save and load the Program but not the results.

## Your Environment

* Version used: QISKIT 0.3
* Environment name and version (e.g. Python 3.6.1):
* Operating System and version: OSX&Windows&Linux

**Comment by atilag** [comment]
There's a change on how we are going to approach this issue, so let's close it.
