### ISSUE TITLE
Custom Gate construction uses private methods and is unintuitive

### ISSUE THREAD

**Issue by eddieschoute** [QISKit/qiskit-sdk-py#329]
It is currently unclear how a user can construct their own custom gates _dynamically_ for use in a QuantumCircuit. In OpenQASM it is clear how to define a custom gate using a gate declaration, but doing the same in QISKit is unclear.

## Expected Behavior
Documentation describing how to construct a custom gate to perform on a circuit should be present. Maybe even a method on the `QuantumCircuit` class. Or some way to define a custom gate dynamically, i.e. without subclassing `CompositeGate`.

## Current Behavior
An example I could find is [this](https://github.com/QISKit/qiskit-sdk-py/blob/78ef075fe8e28957db954448556e69345c6ca8db/examples/python/basic_optimize.py). Excerpt:
```py
composite_gate_1 = CompositeGate("composite1", [],
                                 [quantum_r[x] for x in range(4)])

composite_gate_1._attach(CnotGate(quantum_r[0], quantum_r[1]))
circuit._attach(composite_gate_1)
```

First off, it is clear that this uses the private method `_attach` to construct the composite gate. Furthermore, it uses gate classes (e.g. `CnotGate`) as opposed to the often-used `circuit.cx(·)` notation in QISKit.

## Possible Solution
It would be great if one could construct a _subcircuit_ with the same ease as constructing a circuit, and then be able to call that subcircuit from the main circuit. The way this compiles to OpenQASM should also be fairly apparent.

On another note, I was also confused by the inability to call other circuits inside a `QuantumProgram`, what is the point of a `Program` class if it just contains a list of disjunctive circuits? Why can it contain multiple circuits? To me, currently, it seems to just be wrapper for running on hardware and not a program description.

It would also be nice if an example were included in the pydoc. (As an aside, I'd like more of that in the project too! Had to scratch my head more than once on how to use certain classes and functions.)

## Context
I would like to construct a circuit with certain 'function call'-like behavior. Without constructing a custom gate I'd have to inline the circuit, which is repeated a 100 million times. Thus that would be a serious headache. Further, I'd have to write some code that inlines these functions recursively, with function calls-in-calls (they are acyclic though).

## Your Environment
* Version used: qiskit 0.4.10
* Environment name and version (e.g. Python 3.6.1): python 3.6.4
* Operating System and version: macOS 10.13

**Comment by eddieschoute** [comment]
I tried to get inspiration from the `Unroller` for reading in OpenQASM, but for the example of [an adder with custom gate definitions](https://github.com/QISKit/openqasm/blob/master/examples/generic/bigadder.qasm) the produces circuit simply inlines all the gates referenced in the example.
I ran:
```py
qasm = Qasm(data=qasm_text).parse()
circuit = Unroller(qasm, CircuitBackend()).execute()
```
where `qasm_text` is the string of the adder circuit.

**Comment by eddieschoute** [comment]
Possibly related to #316

**Comment by eddieschoute** [comment]
Closed because duplicate.

**Comment by ardeleanasm** [comment]
@eddieschoute I saw that you use:
```
circuit = Unroller(qasm, CircuitBackend()).execute()
```
I'm using qiskit 0.7.2 and I didn't find an Unroller class. Can you please say what imports did you used and which version of qiskit?

**Comment by eddieschoute** [comment]
It's in the opening post:
>     * Version used: qiskit 0.4.10
I think they moved unrollers or reworked them at some point recently.

**Comment by ardeleanasm** [comment]
Thanks a lot!
