### ISSUE TITLE
coverage3 is used but not required for dev build

### ISSUE THREAD

**Issue by ajavadia** [QISKit/qiskit-sdk-py#330]
In #297, coverage testing was introduced. In the cmake it uses "coverage3",
https://github.com/QISKit/qiskit-sdk-py/blob/cd1b1067deffe645323d6e4d89f1881e2f55cfce/cmake/code-qa.cmake#L34

but this is not part of the requirements:
https://github.com/QISKit/qiskit-sdk-py/blob/cd1b1067deffe645323d6e4d89f1881e2f55cfce/requirements-dev.txt#L6

Consequently, my build from source breaks.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 3.6.1):
* Operating System and version:

**Comment by diego-plan9** [comment]
@ajavadia , can you elaborate a bit? Do you mean that `coverage3` (the binary) is not provided when you `pip install coverage` (the package)? If so, can you provide more info about your installation - the wheels for Python 3 seem to have an alias for `coverage3` in most cases:

```
[console_scripts]
coverage = coverage.cmdline:main
coverage-3.6 = coverage.cmdline:main
coverage3 = coverage.cmdline:main
```

And [the docs](http://coverage.readthedocs.io/en/coverage-4.5.1/cmd.html) seem to point in that direction as well:
> When you install coverage.py, a command-line script simply called coverage is placed in your Python scripts directory. To help with multi-version installs, it will also create either a coverage2 or coverage3 alias, and a coverage-X.Y alias, depending on the version of Python you’re using. For example, when installing on Python 2.7, you will be able to use coverage, coverage2, or coverage-2.7 on the command line.

**Comment by ajavadia** [comment]
Hi @diego-plan9, thanks. I think the problem was with the pip version I was using on the new linux environment I was testing on. It is fixed now.
