### ISSUE TITLE
Mapper bug alters already conforming circuits, and inserts operation after measurement

### ISSUE THREAD

**Issue by ajavadia** [QISKit/qiskit-sdk-py#342]
Bug#1: A random initial layout is chosen by the mapper. This is undesirable when users explicitly use CX gates that are supported by backends. 

Bug#2: The mapper sometimes reuses a measured qubit for further operation. This is rejected by real backends. It is, however, functionally correct because the measured qubit is only used as a swap intermediary.

## Expected Behavior

If the circuit already conforms to backend topology, don't alter it. The user probably wants the exact same qubits.
Don't reuse measured qubits if the backend is real.

## Current Behavior

A manifestation of this bug is in the "quantum emoticon" example, as reported many times.
This input circuit:
![image](https://user-images.githubusercontent.com/8622381/37472700-183c8954-2843-11e8-93aa-09912c9b383a.png)

gets rewritten to this (**Notice what happens to qubit 6 after it is measured.**)
![image](https://user-images.githubusercontent.com/8622381/37472833-61775036-2843-11e8-8296-695155329c3a.png)

## Possible Solution

Current workarounds are:
1. Insert barrier before measurements, ensuring no reordering of gates and measurements occurs.
2. Specify an initial layout manually (for the emoticon example, the simple layout of i-to-i works).

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 3.6.1):
* Operating System and version:

**Comment by diego-plan9** [comment]
Fixed via #347
