### ISSUE TITLE
make run_tutorial wont work on Mac with XCode

### ISSUE THREAD

**Issue by jigar1859** [QISKit/qiskit-sdk-py#36]
$ make run_tutorial

ERROR:
make: *** No rule to make target `run_tutorial'.  Stop.

**Comment by jaygambetta** [comment]
Hi @jigar1859. Thanks for pointing this out. 

This is an error and we are working on fixing the readme/documentation and a pip installation over the next couple of weeks. 

We split the tutorials from the main SDK. To run the tutorials please go to https://github.com/QISKit/qiskit-tutorial and make sure you have the sdk at version r0.3.

**Comment by jigar1859** [comment]
Thanks @jaygambetta... It's works fine now with the new r.03... appreciate your reply.

Regards,
Jigar Thakkar
