### ISSUE TITLE
RZ calls nonexistent attribute 'sz'

### ISSUE THREAD

**Issue by eddieschoute** [QISKit/qiskit-sdk-py#362]
When applying an RZ gate to a circuit, the function calls the `sz` attribute on the Register, which does not exist.

## Expected Behavior
Probably `.size` should be called instead.

## Current Behavior
When calling `rz` in the following manner:
```py
circuit.rz(gate.timestep, target)
```
with target a `QuantumRegister` I get the exception
```
  File "/Users/eddie/dev/quantum-circuit-layout/.venv/lib/python3.6/site-packages/qiskit/extensions/standard/rz.py", line 60, in rz
    for j in range(q.sz):
AttributeError: 'QuantumRegister' object has no attribute 'sz'
```

## Possible Solution
Replace `.sz` by `.size`

## Steps to Reproduce (for bugs)
Should be fairly self-explanatory.

## Context
Add an rz gate to my circuit.

## Your Environment
* Version used: 0.4.11
* Environment name and version (e.g. Python 3.6.1): 3.6.4
* Operating System and version: macOS 10.13

**Comment by eddieschoute** [comment]
`rx` and `ry` contain the same code. (You should apply DRY here)

**Comment by ajavadia** [comment]
This is tracked in #352. I will push a fix soon.

**Comment by eddieschoute** [comment]
Sorry about the duplication

**Comment by ajavadia** [comment]
no worries, thanks for looking at the code in detail and raising the issues.
