### ISSUE TITLE
make test fails locally

### ISSUE THREAD

**Issue by ajavadia** [QISKit/qiskit-sdk-py#367]
`make test` fails locally, possibly due to the configuration of hubs in the Qconfig.
This has not been an issue with travis and submitted PRs.

## Steps to Reproduce (for bugs)

`python -m unittest -v test.python.test_api_ibmq.TestApiHub`

**Comment by diego-plan9** [comment]
It seems the original tests fell out of sync with the current hubs implementation, and might fail under specific circumstances - I'll look into it!
