### ISSUE TITLE
CMake error on mac OS

### ISSUE THREAD

**Issue by ajavadia** [QISKit/qiskit-sdk-py#393]
Currently the simulator is built like this:
`mkdir out; cd out; cmake ..; make`

On some versions of Apple Clang, the above fails due to problems with static linking. A workaround exists:
`mkdir out; cd out; cmake -DSTATIC_LINKING=False ..; make`

A fix will be available soon. This is just to track, and to offer a temporary fix.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: 0.4.11
* Environment name and version (e.g. Python 3.6.1): Python 3.6.1
* Operating System and version: Mac OS 10.13.3, Clang-900.0.39.2, LLVM 9.0.0

**Comment by diego-plan9** [comment]
Fixed by #468
