### ISSUE TITLE
Unable to locate/find sdk folder in Qiskit

### ISSUE THREAD

**Issue by 4Sheetal** [QISKit/qiskit-sdk-py#400]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 3.6.1):
* Operating System and version:

**Comment by atilag** [comment]
@4Sheetal I guess something slept through while creating the issue, right? There's no information attached.
Gonna close the issue.
