### ISSUE TITLE
Why is stable branch ahead of master branch?

### ISSUE THREAD

**Issue by rraymondhp** [QISKit/qiskit-sdk-py#405]
The stable branch is ahead of master, which is not a good practice. 
## Expected Behavior

Make sure that stable only accepts changes that passed the tests. Also, master should be ahead of stable, and stable is behind master. 

## Current Behavior

`This branch is 20 commits ahead, 51 commits behind master. `
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 3.6.1):
* Operating System and version:

**Comment by atilag** [comment]
It's not a good practice, totally agree! But there are times when this is can occur temporarily, as is the case right now. We had to fix something in `stable` to quickly release a new version, this has broke synchrony between `master` and `stable`.
There's a new PR #407 intended to improve this situation though.

**Comment by ajavadia** [comment]
The changes are synced, and there is no conflict. We are temporarily holding some files around for various backward compatibility reasons. The situation will improve in a few weeks when we won't have to anymore.
