### ISSUE TITLE
Unable to find sdk folder

### ISSUE THREAD

**Issue by 4Sheetal** [QISKit/qiskit-sdk-py#406]
general summary of the issue in the Title above -->

## Expected Behavior
sir, i have installed Anaconda 3 with the help of Qiskit Documentaionthen i choose option A for Qiskit installation i followed all the steps as mention in documentation. i must have sdk folder in requirement. txt. so that i can run IBM experiments 

## Current Behavior
but  there is no Qconfig.py.  as u can see an upload jpg image.

## Possible Solution
i do not what is the solution of this beacuse i am new user.

## Context
<!---i am trying to accomplish IBM quantum experiment with the help of Qiskit

## Your Environment

* Version used: Anaconda 3
* Environment name and version (e.g. Python 3.6.1):
* Operating System and version: windows 8.1 64 bit
![image](https://user-images.githubusercontent.com/38429119/38857809-cc0efe30-4247-11e8-8c38-f36f268d9f34.png)

**Comment by diego-plan9** [comment]
Closing - please reopen or comment back if further help is needed.
