### ISSUE TITLE
A bug in circuit initialization

### ISSUE THREAD

**Issue by chunfuchen** [QISKit/qiskit-sdk-py#409]
Providing incorrect number of arguments.
Here: https://github.com/QISKit/qiskit-sdk-py/blob/master/qiskit/extensions/quantum_initializer/_initializer.py#L103

The method `circ.initialize` only takes 2 arguments but 3 is given. (https://github.com/QISKit/qiskit-sdk-py/blob/master/qiskit/extensions/quantum_initializer/_initializer.py#L438)

## Possible Solution
change that line to `self._modifiers(circ.initialize(self.param, self.arg))`

**Comment by diego-plan9** [comment]
Thanks @chunfuchen ! It has been fixed in #443 and will be included in the next release.
