### ISSUE TITLE
Invalid QASM error with a very simple circuit.

### ISSUE THREAD

**Issue by t-imamichi** [QISKit/qiskit-sdk-py#417]
QISKit 0.4.13 seems to generate an invalid QASM for real devices.

## Expected Behavior
QISKit executes the circuit without error.
```
from qiskit import QuantumProgram
import Qconfig
qp = QuantumProgram()
qp.set_api(Qconfig.APItoken, Qconfig.config['url'])
qr = qp.create_quantum_register('qr',1)
cr = qp.create_classical_register('cr',1)
qc = qp.create_circuit('sample',[qr],[cr])
qc.h(qr[0])
result = qp.execute('sample', backend='ibmqx4')
print(result.get_counts('sample'))
```
https://gist.github.com/t-imamichi/f4afd05e7b510f2ab259bca68f44c022

## Current Behavior
```
WARNING:IBMQuantumExperience.IBMQuantumExperience:Got a 400 code response to https://quantumexperience.ng.bluemix.net/api/Jobs?access_token=XXX: {"error":{"status":400,"message":"Error parsing QASM. Error parsing qasm number 0. Identifiers must begin with a lowercase letter","code":"QASM_NOT_VALID","statusCode":400}}
qiskit._resulterror.ResultError: QASM_NOT_VALID: Error parsing QASM. Error parsing qasm number 0. Identifiers must begin with a lowercase letter
```

## Possible Solution
no idea.

## Steps to Reproduce (for bugs)
https://gist.github.com/t-imamichi/f4afd05e7b510f2ab259bca68f44c022
1. Set Qconfig appropriately
2. Run the script
3.
4.

## Your Environment

* Version used: qiskit 0.4.13
* Environment name and version (e.g. Python 3.6.1): Python 3.6.5
* Operating System and version: Ubuntu 16.04

**Comment by ajavadia** [comment]
fixed in #418
