### ISSUE TITLE
Verify backends interchangeability

### ISSUE THREAD

**Issue by yaelbh** [QISKit/qiskit-sdk-py#426]
Directory test/python currently contains (in PR #421) an empty test file named test_simulator_interfaces.py.
Write this test. It will run the various simulators on various inputs, using the backend wrappers in qiskit/backends/local.
Then it will verify that the outputs are similar (distinguish between regular and state vector simulators, in terms of inputs validity and expected outputs; expect identical outputs across state vector simulators, and find a way to compare output of regular simulators containing measurements).

**Comment by ajavadia** [comment]
This was done in #435, where several cross-simulator tests were added. But feel free to add more later. I will close this as resolved.
