### ISSUE TITLE
Unexpected behaviour for ibmqx5

### ISSUE THREAD

**Issue by decodoku** [QISKit/qiskit-sdk-py#439]
Output for a repetition code run gives significantly different behaviour than expected.

## Expected Behavior
Repetition codes were run on *ibmqx5* with an encoded bit value of `0`. The output should be `0` on all qubits. Given noise levels and previous results, it can be expected that `1` will instead be output for each qubit for 10-20% of the samples. This is seen for codes of size d=3 to d=7 using the implementation [here](https://github.com/decodoku/repetition_code/blob/master/repetition_code.ipynb).

## Current Behavior
For a d=8 code, it is found that some qubits output `1` for 50-80% of the samples. A comparison of recent runs showing the expected behaviour for d=7, and the unexpected behaviour for d=8, can be found [here](https://github.com/decodoku/Misc_QISKit_Things/blob/master/RepetitionCodeBug.ipynb).

## Possible Solution
If this is noise, a solution is obviously outside the scope of the SDK. However, it could be that something strange is going on in the process of taking the QASM and turning it into a pulse sequence. I'd suggest looking further down the stack for a possible bug.

## Steps to Reproduce (for bugs)
This issue relates to jobs created by [this file](https://github.com/decodoku/repetition_code/blob/master/repetition_code.ipynb). A stripped down version focussed on the job with the issue can be found [here](https://github.com/decodoku/Misc_QISKit_Things/blob/master/Simple_Repetition.ipynb). Results for runs with and without the issue are compared [here](https://github.com/decodoku/Misc_QISKit_Things/blob/master/RepetitionCodeBug.ipynb).

## Your Environment
* Python 3.6.0
* IBMQuantumExperience      1.9.0
* qiskit                    0.4.14

**Comment by jaygambetta** [comment]
I think we close this as its not in the sdk. But i let Hanhee and you debug to determine if it is the pulse generating code.
