### ISSUE TITLE
JSONBackend expects basis_gates as a list, receives a string

### ISSUE THREAD

**Issue by r3versi** [QISKit/qiskit-sdk-py#444]
As _openquantumcompiler.dag2json has been reintroduced  by commit https://github.com/QISKit/qiskit-sdk-py/commit/77ffd963798e57b0f0650628048dd2ac19a30a16 it is not compatible with JSONBackend as it expects to get as argument a list of basis gates, not a comma separated string.

A possible solution is to substitute 
https://github.com/QISKit/qiskit-sdk-py/blob/07b2485cb0c05d3649de83ece9be1c50c3aff979/qiskit/_openquantumcompiler.py#L36 
by 
``    return DagUnroller(dag_circuit, JsonBackend(basis_gates.split(",")).execute()``

**Comment by ajavadia** [comment]
Thanks for the catch @r3versi!

**Comment by diego-plan9** [comment]
For reference, the fix was included in 0.4.15 as well.
