### ISSUE TITLE
qiskit_simulator.exe crashes on Windows 7

### ISSUE THREAD

**Issue by t-imamichi** [QISKit/qiskit-sdk-py#456]
qiskit_simulator.exe crashes on Windows 7

## Expected Behavior
qiskit_simualtor exits normally.

## Current Behavior
Just the command `qiskit_simulator.exe` causes the crash.
The crash window is as follows (sorry for the Japanese message).
![image](https://user-images.githubusercontent.com/31178928/39823003-08f9abd2-53e7-11e8-8d2e-9c32164d2199.png)

## Possible Solution
no idea.

## Steps to Reproduce (for bugs)
1. Go to the qiskit directory
2. Run the command `qiskit_simulator.exe`
3. It crashes.

## Your Environment

* Version used: qiskit 0.4.15
* Environment name and version (e.g. Python 3.6.1): Python 3.6.5
* Operating System and version: Windows 7

**Comment by atilag** [comment]
Hi @t-imamichi ,
I could run the simulator without problems on Windows 7 (*64 bits*), using Qiskit 0.4.15 and latest 0.5.1.
Are you running on 64 bits?

**Comment by t-imamichi** [comment]
Yes, I am using Windows 7 SP1 64bit with 8GB memory. The simulator of the latest 0.5.1 does not work.

**Comment by t-imamichi** [comment]
I confirm that qiskit 0.5.2 solves the issue. Great job!
