### ISSUE TITLE
Better offline support.

### ISSUE THREAD

**Issue by atilag** [QISKit/qiskit-sdk-py#49]
We should allow the usage of the SDK in offline scenarios. This will restrict the user to deal with local simulators only. If the user tries to access some online feature, we will throw a controlled exception.

## Current Behavior
If there's no Internet connection, the QuantumProgram class will throw and exit.

## Steps to Reproduce (for bugs)

1. Switch off networking
2. Run your program (which highly probable uses QuantumProgram class)
3. Program stops because of connection related exceptions.

## Your Environment

* Version used: 0.3.4 
* Environment name and version (e.g. Python 3.6.1): All supported versions
* Operating System and version: All supported versions

**Comment by chriseclectic** [comment]
I use it offline all the time, you just have to comment out or remove the line of code `Q_program.set_api(...)` since it is the `set_api` method that fails when there is no internet connection.

It would be better handled if the `set_api` method used a try block, something like:
```python
def set_api(self, token, url, verify=True):
    try:
        self.__api = IBMQuantumExperience(token, {"url": url}, verify)
        self.__ONLINE_BACKENDS = self.online_backends()
        self.__api_config["token"] = token
        self.__api_config["url"] = {"url": url}
    except:
        print('>>> Unable to communicate with IBMQuantumExperience')
        print('>>> QISKit is in offline mode.')
```

**Comment by atilag** [comment]
Yes, this is the main point to fix. But I think is safer/more consistent if we wrap in a try block every call to the API so we can rise a controlled exception, or behave the way we want depending on the case.
