### ISSUE TITLE
İBM License error

### ISSUE THREAD

**Issue by nazimran** [QISKit/qiskit-sdk-py#73]
I can get the QIS Kit / qis kit-sdk-play code and change it as I want.
I have a right to this.

If you are into Python, all other Licenses are null and void.

and I can change and distribute the open code.

https://www.python.org/download/releases/2.7/license/

IBM do not be greedy.

I HOPE

Apache License  invalid .. 

MBİ AÇ GÖZLÜ OLMA.

**Comment by atilag** [comment]
Not sure what you mean... but, you can get the code and do whatever you want with it while respecting Apache 2 license.
We love to share :) !!
