### ISSUE TITLE
Bug in mapping?

### ISSUE THREAD

**Issue by itoko** [QISKit/qiskit-sdk-py#81]
Measurement results differ in compiling with/without coupling_map.

## Expected Behavior

With this QASM (`coupling_map=None`), expected measurement results are {'1001', '0001'}
```
OPENQASM 2.0;
include "qelib1.inc";
qreg q[4];
creg c[4];
// -X-.-----
// -Y-+-S-.-
// -Z-.-T-+-
// ---+-H---
x q[0];
y q[1];
z q[2];
cx q[0], q[1];
cx q[2], q[3];
s q[1];
t q[2];
h q[3];
cx q[1], q[2];
measure q[0] -> c[0];
measure q[1] -> c[1];
measure q[2] -> c[2];
measure q[3] -> c[3];
```

## Current Behavior

{'0000', '1000'} are obtained with `coupling_map = {0: [2], 1: [2], 2: [3], 3: []}`

## Steps to Reproduce (for bugs)

```
        qp = QuantumProgram()
        qp.load_qasm_file('qasm_above.qasm', name='test2')
        coupling_map = {0: [2], 1: [2], 2: [3], 3: []}
        result1 = qp.execute(["test2"], backend="local_qasm_simulator", coupling_map=coupling_map)
        print(result1.get_counts("test2"))
        result2 = qp.execute(["test2"], backend="local_qasm_simulator", coupling_map=None)
        print(result2.get_counts("test2"))
```

**Comment by lbello** [comment]
I cannot assign myself this issue. But I would like to have a shot to see if I can fix it... just FYI

**Comment by lbello** [comment]
The attached patch fixes this issue.

If the first layer is trivial, it should not be ignored. Fixes #81
[mapping.patch.zip](https://github.com/QISKit/qiskit-sdk-py/files/1354150/mapping.patch.zip)

**Comment by rraymondhp** [comment]
@itoko  Can you check the patch fix? 
@lbello  thanks for the fixing. Is it possible to create a branch and work and that branch so that it is easier to merge later?

**Comment by lbello** [comment]
@rraymondhp not sure what do you mean? create a branch in `QISKit/qiskit-sdk-py`? The PR #105 is fixing it.

**Comment by rraymondhp** [comment]
Thanks. I meant your fix is important and should be pulled asap. 

And, you have already made a PR to fix the issue! Thanks again. 
My colleague has confirmed that it worked on his instances.
