### ISSUE TITLE
Bug in cu3 implementation

### ISSUE THREAD

**Issue by yoonbo** [QISKit/qiskit-sdk-py#86]
cu3(pi, 0, pi) gate should work as controlled X gate, but it is not.

## Expected Behavior

cx: (1, 0) ---> (0, 1)
cu3(pi, 0, pi) : (1, 0) ---> (0, 1)

## Current Behavior

cx: (1, 0) ---> (0, 1)
cu3(pi, 0, pi) : (1, 0) ---> (0, -i)

## Steps to Reproduce (for bugs)

```
import numpy as np

sys.path.append("../qiskit-sdk-py/")

from qiskit import QuantumProgram
import Qconfig

np.set_printoptions(precision=2)

Q_program = QuantumProgram()
n = 2
q = Q_program.create_quantum_register('q', n)
c = Q_program.create_classical_register('c', n)
  
state = Q_program.create_circuit('bug', [q], [c])

state.x(q[0])
state.cx(q[0], q[1])

state.measure(q[1], c[1])

backend = 'local_qasm_simulator'
result = Q_program.execute(['bug'], backend=backend, shots=1, silent = True)
print("Controlled X gate:")
print(result.get_data('bug')['quantum_state'])

print("")


Q_program = QuantumProgram()
n = 2
q = Q_program.create_quantum_register('q', n)
c = Q_program.create_classical_register('c', n)
  
state = Q_program.create_circuit('bug', [q], [c])

state.x(q[0])
state.cu3(np.pi, 0.0, np.pi, q[0], q[1])

state.measure(q[1], c[1])

backend = 'local_qasm_simulator'
result = Q_program.execute(['bug'], backend=backend, shots=1, silent = True)
print("CU3(pi, 0, pi) gate:")
print(result.get_data('bug')['quantum_state'])
```

Above code prints out

```
Controlled X gate:
[ 0.+0.j  0.+0.j  0.+0.j  1.+0.j]

CU3(pi, 0, pi) gate:
[  0.00e+00+0.j   0.00e+00+0.j   0.00e+00+0.j   6.12e-17-1.j]
```

## Your Environment

* Version used: 0.3.5
* Environment name and version (e.g. Python 3.6.1): Python 3.6.2
* Operating System and version: OSX

**Comment by rraymondhp** [comment]
Hi, thanks for the post. 

But, essentially the state 
`[ 0.+0.j  0.+0.j  0.+0.j  1.+0.j]` and the state `[  0.00e+00+0.j   0.00e+00+0.j   0.00e+00+0.j   6.12e-17-1.j]` are the same up to global phase `-j`. I have confirmed that the `cu3` with target `1` results in essentially the same state with `cx` up to the global phase `-j`. 

Please refer to: 
https://en.wikipedia.org/wiki/Quantum_state
```... A unit vector is usually picked, but its phase factor can be chosen freely anyway. Nevertheless, such factors are important when state vectors are added together to form a superposition.```

**Comment by jaygambetta** [comment]
@yoonbo and @rraymondhp this is correct. It is not a bug it is just a global phase that quantum computers can't be see. I suggest if you look at |<psi_expected|psi_made>|^2 and if this is one then the states are the same.

**Comment by rraymondhp** [comment]
Thanks. I also wrote about the global phase equivalence of `u3` gate in the tutorial below:
https://nbviewer.jupyter.org/github/QISKit/qiskit-tutorial/blob/master/1_introduction/quantum_gates_and_linear_algebra.ipynb
