### ISSUE TITLE
logging system is needed?

### ISSUE THREAD

**Issue by lbello** [QISKit/qiskit-sdk-py#96]
There is room for improvement in the way qiskit prints debugging info.
In the current situation some API calls have a `silent` argument (eg. `QuantumProgram.compile` ) and some other calls have a `verbose` argument (eg. `_mapping.swap_mapper`), with opposite meaning.

Debugging is already painful enough :) A better logging system would also make easier to get debug infor for bug reports. Something like [logging](https://docs.python.org/3/library/logging.html) is probably the way to go.

**Comment by atilag** [comment]
Hi Luciano, I already have filed an issue (#88) about this. You are right, it's a low priority bug and we think it's a good candidate for new contributors.
